// Spotify playlist writes via the app owner's own account (Authorization
// Code flow, not the Client Credentials flow spotify.ts uses for read-only
// album-art lookups). This is the single-account workaround for building
// per-user Weekly Jam playlists without per-user Spotify OAuth — see the
// plan doc for why (60 active users is past Spotify Dev Mode's 25-user cap
// for per-user OAuth).

const TOKEN_URL = "https://accounts.spotify.com/api/token";

// Module-level cache: fine for a single-owner-account job (one warm server
// instance, run once a week), not a distributed cache — same tradeoff as
// spotify.ts's Client Credentials token cache.
let cachedOwnerToken: { value: string; expiresAt: number } | null = null;

/**
 * Refreshes the app owner's Spotify access token via SPOTIFY_OWNER_REFRESH_TOKEN
 * (obtained once via the /api/admin/spotify/connect + callback bootstrap flow).
 * Returns null on any failure (missing config, network error) rather than
 * throwing — callers should treat playlist building as best-effort.
 */
export async function getOwnerAccessToken(): Promise<string | null> {
  const clientId = process.env.SPOTIFY_CLIENT_ID;
  const clientSecret = process.env.SPOTIFY_CLIENT_SECRET;
  const refreshToken = process.env.SPOTIFY_OWNER_REFRESH_TOKEN;
  if (!clientId || !clientSecret || !refreshToken) return null;

  if (cachedOwnerToken && cachedOwnerToken.expiresAt > Date.now()) {
    return cachedOwnerToken.value;
  }

  let res: Response;
  try {
    res = await fetch(TOKEN_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        Authorization: `Basic ${Buffer.from(`${clientId}:${clientSecret}`).toString("base64")}`,
      },
      body: new URLSearchParams({
        grant_type: "refresh_token",
        refresh_token: refreshToken,
      }).toString(),
      cache: "no-store",
    });
  } catch {
    return null;
  }

  if (!res.ok) return null;

  let body: { access_token?: string; expires_in?: number };
  try {
    body = await res.json();
  } catch {
    return null;
  }

  if (!body.access_token) return null;

  cachedOwnerToken = {
    value: body.access_token,
    // Refresh 60s early so a token doesn't expire mid-flight.
    expiresAt: Date.now() + (body.expires_in ?? 3600) * 1000 - 60_000,
  };
  return cachedOwnerToken.value;
}

/**
 * Creates a new playlist (if `existingPlaylistId` is null) or replaces the
 * tracks of an existing one, under the owner's Spotify account. Uses
 * /me/playlists rather than /users/{id}/playlists — the latter 403s unless
 * the path id matches the token's account exactly, which /me sidesteps.
 * Returns null on any failure — best-effort, one user's failure shouldn't
 * affect others.
 */
export async function upsertWeeklyPlaylist(
  ownerAccessToken: string,
  opts: { existingPlaylistId: string | null; name: string; trackUris: string[] },
): Promise<{ id: string; url: string } | null> {
  let playlistId = opts.existingPlaylistId;

  if (!playlistId) {
    let createRes: Response;
    try {
      createRes = await fetch(`https://api.spotify.com/v1/me/playlists`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${ownerAccessToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name: opts.name,
          public: false,
          description: "Auto-generated by Rogha's Weekly Jam.",
        }),
        cache: "no-store",
      });
    } catch {
      return null;
    }
    if (!createRes.ok) return null;

    let createBody: { id?: string };
    try {
      createBody = await createRes.json();
    } catch {
      return null;
    }
    if (!createBody.id) return null;
    playlistId = createBody.id;
  }

  // Spotify caps this endpoint at 100 URIs per request — plenty for a
  // friend-group Jam (own track + friends' tracks), so no pagination needed.
  // Path is /items, not /tracks — Spotify's Feb 2026 migration renamed this
  // endpoint (the old /tracks path 403s instead of erroring clearly).
  let tracksRes: Response;
  try {
    tracksRes = await fetch(`https://api.spotify.com/v1/playlists/${playlistId}/items`, {
      method: "PUT",
      headers: {
        Authorization: `Bearer ${ownerAccessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ uris: opts.trackUris.slice(0, 100) }),
      cache: "no-store",
    });
  } catch {
    return null;
  }
  if (!tracksRes.ok) return null;

  return { id: playlistId, url: `https://open.spotify.com/playlist/${playlistId}` };
}
